### Kata 1 - Sum The Largest Numbers
#### Create a function named sumLargestNumbers that will receive a list of numbers and return the sum of the two largest numbers in that array.

In [116]:
def sumLargesNumbers(nums):
    # Takes a list and return the sum of the 2 largest numbers in that list.
    
    # sumLargestNumbers([10, 4, 34, 6, 92, 2])
    # >>> 126

    return(f'The largest 2 numbers sum up to: {nums.sort[-2:].sum()}')

#### Test:

In [118]:
print(sumLargestNumbers([1, 10]))
print(sumLargestNumbers([1, 2, 3]))
print(sumLargestNumbers([10, 4, 34, 6, 92, 2]))

The largest 2 numbers in the list sum up to: 11
The largest 2 numbers in the list sum up to: 5
The largest 2 numbers in the list sum up to: 126


### Kata 2 - Conditional Sums
#### Create a function named conditionalSum that will be given a list of numbers and a condition, in this case odd or even. Given this condition, add up only the values which match that condition. If no values match the condition, return 0.

In [340]:
def conditionalSum(nums, condition):
    # Takes a list and condition (odd or even), sums up the values in the list that match the condition.
    # If no values match the condition, return 0.
    
    # conditionalSum([1, 2, 3, 4, 5], "even")
    # >>> 6
    # conditionalSum([1, 2, 3, 4, 5], "odd")
    # >>> 9
    # conditionalSum([13, 88, 12, 44, 99], "even")
    # >>> 144
    # conditionalSum([], "odd")
    # >>> 0
    
    total_value = 0
    
    for n in nums:
        if condition == 'even' and n % 2 == 0:
            total_value += n
    
        elif condition == 'odd' and n % 2 == 1:
            total_value += n
        
    return(f'The sum of all {condition} numbers is: {total_value}.')

#### Test:

In [341]:
print(conditionalSum([1, 2, 3, 4, 5], "even"))
print(conditionalSum([1, 2, 3, 4, 5], "odd"))
print(conditionalSum([13, 88, 12, 44, 99], "even"))
print(conditionalSum([], "odd"))

The sum of all even numbers is: 6.
The sum of all odd numbers is: 9.
The sum of all even numbers is: 144.
The sum of all odd numbers is: 0.


### Kata 3 - Vowels
#### Create a function named numberOfVowels that will receive a string and return the number of vowels in that string.

In [359]:
def numberOfVowels(string):
    # Takes a string and return the number of vowels in that string.
    
    # numberOfVowels("orange")
    # >>> 3
    
    vowel_count = 0
    vowels = ['a', 'e', 'i', 'o', 'u']
    
    for l in string:
        if l in vowels:
            vowel_count += 1
            
    return(f'There are {vowel_count} vowels in the string.')

#### Test:

In [360]:
print(numberOfVowels("orange"))
print(numberOfVowels("lighthouse labs"))
print(numberOfVowels("aeiou"))

There are 3 vowels in the string.
There are 5 vowels in the string.
There are 5 vowels in the string.


### Kata 4 - Instructors Names
#### Create a function named instructorWithLongestName that will receive a list of instructor dictionaries, and return the object that has the longest name. If there are two instructors with the longest name, return the first one.

In [660]:
def instructorWithLongestName(instructors):
    # Takes a list of instructor dictionary and return the instructor with the longest name and the responding course.
    # If there 2 instructors with the longest name, return the first one.
    
    # instructorWithLongestName([
    # {name: "Samuel", course: "iOS"},
    # {name: "Jeremiah", course: "Data"},
    # {name: "Ophilia", course: "Web"},
    # {name: "Donald", course: "Web"}
    # ]))
    
    # >>> {name: "Jeremiah", course: "Data"}
    
    names = [i['name'] for i in instructors]
    name_len = [len(x) for x in names]
    
    return(instructors[name_len.index(max(name_len))])

#### Test:

In [661]:
print(instructorWithLongestName([
    {'name': 'Samuel', 'course': 'iOS'},
    {'name': 'Jeremiah', 'course': 'Data'},
    {'name': 'Ophilia', 'course': 'Web'},
    {'name': 'Donald', 'course': 'Web'}
]))
print(instructorWithLongestName([
    {'name': 'Matthew', 'course': 'Data'},
    {'name': 'David', 'course': 'iOS'},
    {'name': 'Domascus', 'course': 'Web'}
]))

{'name': 'Jeremiah', 'course': 'Data'}
{'name': 'Domascus', 'course': 'Web'}


### Kata 5 - Percent Encoding
#### Create a function named urlEncode that will receive a string of words, and return that string with all of the whitespace characters converted to %20. If there is whitespace on the outside of the string, like in our second example above, you should only replace the whitespace within the string.

In [693]:
def urlEncode(text):
    # Takes a string of words and replace any space between the words with "%20".
    # Ignore the space before the string and after the string.
    
    # urlEncode(" Lighthouse Labs  ")
    # >>> Lighthouse%20Labs
    
    strip_text = text.strip()
    breakdown = list(strip_text)
    
    for i in range(len(breakdown)):
        if breakdown[i] == ' ':
            breakdown[i] = '%20'
    
    url = ''.join(breakdown)
    
    return(url)

#### Test:

In [692]:
print(urlEncode("Lighthouse Labs"))
print(urlEncode(" Lighthouse Labs  "))
print(urlEncode("blue is greener than purple for sure"))

Lighthouse%20Labs
Lighthouse%20Labs
blue%20is%20greener%20than%20purple%20for%20sure


### Kata 6 - Smart Parking
#### We need to write a function called whereCanIPark() that returns the coordinates of an available parking spot for the vehicle, or returns false if there is no available spot. Our function receives a list of lists representing parking spots, and a string with type of the vehicle that is looking for a parking spot.

In [789]:
def whereCanIPark(parking_lots, vehicle_type):
    # Takes a list of a parking lots and a vehicle type, return a list of cooridnates (X, Y) for an available parking lot according to the vehicle type.
    # Regular cars can only park at R;
    # Small cars can park at R, S;
    # Motorcycles can park at R, S, M.
    # Parking lot in UPPER-CASE means available, lower-case means unavailable.
    # X = columns; Y = rows.
    # If no lot available, return 'false'.
    
    # whereCanIPark(
    #   [
    #     ['s', 's', 's', 's', 's', 's'],
    #     ['s', 'm', 's', 'S', 'r', 's'],
    #     ['s', 'm', 's', 'S', 'r', 's'],
    #     ['S', 'r', 's', 'm', 'r', 's'],
    #     ['S', 'r', 's', 'm', 'R', 's'],
    #     ['S', 'r', 'S', 'M', 'm', 'S']
    #   ],
    #   'motorcycle'
    # )
    # >>> [3, 5]
    
    regular = ['R']
    small = ['R', 'S']
    motorcycle = ['R', 'S', 'M']
#     vehicle_types = [regular, small, motorcycle]
    
    for row in parking_lots:
        for column in row:
            if column.islower():
                continue
            elif column.isupper() and column == vehicle_type[0].upper():
                X = row.index(column)
                Y = parking_lots.index(row)
                return(X, Y)
    return('false')

#### Test:

In [790]:
print(whereCanIPark(
  [
    # COLUMNS ARE X
    # 0    1    2    3    4    5
    ['s', 's', 's', 'S', 'R', 'M'], # 0 ROWS ARE Y
    ['s', 'M', 's', 'S', 'r', 'M'], # 1
    ['s', 'M', 's', 'S', 'r', 'm'], # 2
    ['S', 'r', 's', 'm', 'r', 'M'], # 3
    ['S', 'r', 's', 'm', 'r', 'M'], # 4
    ['S', 'r', 'S', 'M', 'M', 'S']  # 5
  ],
  'regular'
))

print(whereCanIPark(
  [
    ['M', 'M', 'M', 'M'],
    ['M', 's', 'M', 'M'],
    ['M', 'M', 'M', 'M'],
    ['M', 'M', 'r', 'M']
  ],
  'small'
))

print(whereCanIPark(
  [
    ['s', 's', 's', 's', 's', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['s', 'm', 's', 'S', 'r', 's'],
    ['S', 'r', 's', 'm', 'r', 's'],
    ['S', 'r', 's', 'm', 'R', 's'],
    ['S', 'r', 'S', 'M', 'm', 'S']
  ],
  'motorcycle'
))

(4, 0)
false
(3, 5)


### Kata 7 - In the Air Tonight
#### For this challenge, we will implement a function called checkAir(), which will check a collection of air samples. The function will take in two arguments. The first argument is a list of strings, where each string represents a small air sample that is either clean or dirty. The second argument is a number representing the highest acceptable amount of dirty samples. For example, a threshold of 0.4 means that there must be less than 40% of total samples classified as dirty for our air to be considered clean. Our function must return Polluted if there are too many dirty air samples, or Clean if the proportion of dirty samples is below the threshold.

In [816]:
def checkAir(samples, threshold):
    # Takes a list of samples, each sample is either 'clean' or 'dirty', if the percentage of the 'dirty' sample in the list samples exceed the given threshold, return 'Polluted';
    # if not, return 'Clean'.
    
    # print(checkAir(
    #  ['clean', 'clean', 'dirty', 'clean', 'dirty', 'clean', 'clean', 'dirty', 'clean', 'dirty'],
    #  0.3
    # ))
    # >>> Polluted
    
    pollution_level = 0
    sample_size = len(samples)
    
    
    for sample in samples:
        if sample == 'dirty':
            pollution_level += 1
    
    pollution_percentage = pollution_level / sample_size
    
    if pollution_percentage >= threshold:
        return('Polluted')
    else:
        return('Clean')

#### Test:

In [815]:
print(checkAir(
  ['clean', 'clean', 'dirty', 'clean', 'dirty', 'clean', 'clean', 'dirty', 'clean', 'dirty'],
  0.3
))

print(checkAir(
  ['dirty', 'dirty', 'dirty', 'dirty', 'clean'],
  0.25
))

print(checkAir(
  ['clean', 'dirty', 'clean', 'dirty', 'clean', 'dirty', 'clean'],
  0.9
))

Polluted
Polluted
Clean


### (Stretch) Kata 6 - Repeating Numbers
#### Create a function named repeatNumbers that will return a string with each of the given values repeated the appropriate number of times. If there are multiple sets of values each set should be separated by a comma. If there is only one set of values then you should omit the comma.

In [21]:
def repeatNumbers(data):

    # print(repeatNumbers([[1, 10]]))
    # print(repeatNumbers([[1, 2], [2, 3]]))
    # print(repeatNumbers([[10, 4], [34, 6], [92, 2]]))

    # >>> 1111111111
    # >>> 11, 222
    # >>> 10101010, 343434343434, 9292
    
    res = [str(datum[0]) * datum[1] for datum in data]
    return(res)

#### Test:

In [22]:
print(repeatNumbers([[1, 10]]))
print(repeatNumbers([[1, 2], [2, 3]]))
print(repeatNumbers([[10, 4], [34, 6], [92, 2]]))

['1111111111']
['11', '222']
['10101010', '343434343434', '9292']


### (Stretch) Kata 7 - Case Maker
#### Create a function named camelCase that will convert a string to a camel case, and return the result.

In [71]:
def camelCase(input):
    
    # print(camelCase("this is a string"))
    # print(camelCase("loopy lighthouse"))
    # print(camelCase("supercalifragalisticexpialidocious"))

    # >>> thisIsAString
    # >>> loopyLighthouse
    # >>> supercalifragalisticexpialidocious
    
    breakdown = input.split()
    
    cap = [i.capitalize() for i in breakdown[1 : len(breakdown)]]
    cap.insert(0, breakdown[0])
    
    res = ''.join(cap)
    
    return(res)

#### Test:

In [69]:
print(camelCase("this is a string"))
print(camelCase("loopy lighthouse"))
print(camelCase("supercalifragalisticexpialidocious"))

thisIsAString
loopyLighthouse
supercalifragalisticexpialidocious


### (Stretch) Kata 8 - Multiplication Table
#### Create a function named multiplicationTable that receives a number maxValue as input and creates a square multiplication table where maxValue is the largest value in the table.

In [174]:
def multiplicationTable(maxValue):

    # print(multiplicationTable(5))

    # >>> 1 2 3 4 5
    #     2 4 6 8 10
    #     3 6 9 12 15
    #     4 8 12 16 20
    #     5 10 15 20 25 
    
    import numpy as np
    
    table = np.zeros((maxValue, maxValue))
    
    stand = np.array(range(1, maxValue+1))
    
    for i in range(maxValue):
        table[i,:] = (i+1) * stand
    return(table)

#### Test:

In [175]:
print(multiplicationTable(1))
print(multiplicationTable(5))
print(multiplicationTable(10))

[[1.]]
[[ 1.  2.  3.  4.  5.]
 [ 2.  4.  6.  8. 10.]
 [ 3.  6.  9. 12. 15.]
 [ 4.  8. 12. 16. 20.]
 [ 5. 10. 15. 20. 25.]]
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]
