In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [6]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
type(A)

numpy.ndarray

In [8]:
A.shape

(3, 2)

In [9]:
x.shape

(4,)

In [10]:
len(x)

4

In [12]:
A_T = A.T
A_T

array([[1, 3, 5],
       [2, 4, 6]])

In [13]:
A_T.shape

(2, 3)

In [14]:
B = np.array([[2, 5], [7, 4], [4, 3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [15]:
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

In [16]:
D = A + 1
D

array([[2, 3],
       [4, 5],
       [6, 7]])

In [17]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [19]:
C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

In [20]:
C = A.dot(B)
C

array([[10],
       [22],
       [34]])

In [21]:
C.shape

(3, 1)

In [22]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
IA = I.dot(A)
IA

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [24]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [25]:
det_M = np.linalg.det(M)
det_M

-2.0000000000000004

In [26]:
M = np.array([1,2],[3,4],[5,6])
det_M = np.linalg.det(M)
det_M

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [27]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [29]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [31]:
I = A.dot(A_inv)
I

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])