## eigendecomposition exercise

In [1]:
# import numpy
import numpy as np

**Task:** Create a matrix (2x2) called matrix 'A'.


In [2]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

**Task:** Define the function `'shape_2x2'` which checks if a matrix has a (2x2) shape.

In [4]:
"""
Define the function 'shape_2x2' which checks if a matrix has a (2x2) shape.

PARAMS:
    matrix (numpy.ndarray) - matrix to check
RETURN:
    True (bool) - if matrix has shape 2x2
    False (bool) - if matrix has not shape 2x2

"""
def shape_2x2(m):
    if m.shape == (2, 2):
        return(True)
    else:
        return(False)

In [8]:
shape_2x2(A)

True

**Task:** Define the function `'determinant_2x2'` which computes the determinant of a (2x2) matrix.

Do not forget to check the shape of  the input matrix.

In [17]:
"""
Define the function 'determinant_2x2' which computes the determinant of a (2x2) matrix.

PARAMS:
    matrix (numpy.ndarray) - matrix to compute determinant
RETURN:
    det (float) - matrix determinant

"""
def determinant_2x2(m):
    res = A[0,0] * A [1,1] - A[0,1] * A[1,0]
    return(res)

**Task:** Call the function `'determinant_2x2'` on matrix 'A'.

In [19]:
determinant_2x2(A)

-2

**Task:** Compute the eigenvalues of matrix 'A' with numpy.

In [22]:
eigenval, eigenvec = np.linalg.eig(A)

**Task:** Print the eigenvalues.

In [23]:
eigenval

array([-0.37228132,  5.37228132])

**Task:** Print  the eigenvectors.

In [24]:
eigenvec

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

**Task:** Define a function `'eig_2x2'` which computes the eigenvectors and the eigenvalues of 2x2 matrix.

Do not use the np.linalg.eig function. Use your 'shape_2x2' and your 'determinant_2x2' functions. Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of a 2x2 matrix?:

- https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/

In [67]:
"""
Define a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to perform decomposition
RETURN:
    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

"""

def eig_2x2(matrix):
    if not shape_2x2(matrix):
        return None
    
    # sum of matrix diagnal
    matrix_trace = matrix.trace()
    
    # because np.sqrt: np.sqrt(-1) --> NaN, create np.sqrt(-1 + 0j) --> 1j
    inside_sqrt = matrix_trace ** 2 - 4 * determinant_2x2(matrix) + 0j
    
    eigenvalues = [((matrix_trace - np.sqrt(inside_sqrt))/2), 
                  ((matrix_trace + np.sqrt(inside_sqrt))/2)]
    
    # only real part of the number, if imaginary part is 0
    eigenvalues = np.sort(np.array([v.real if v.imag == 0 else v for v in eigenvalues]))
    
    eigenvectors = []
    for eigv in eigenvalues:
        matrix_minus_eig = matrix - eigv * np.eye(matrix.shape[0])
        eigenvector = np.array([-matrix_minus_eig[0, 1], matrix_minus_eig[0, 0]])
    
        # vector with length of 1
        eigenvector_norm = eigenvector / np.linalg.norm(eigenvector)
        eigenvectors.append(eigenvector_norm)
    
    eigenvectors = np.array(eigenvectors).T
    
    return eigenvalues, eigenvectors

**Task:** Call the function `'eig_2x2'` on matrix 'A'.

In [68]:
eig_2x2(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

**Task:** Compare your results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [76]:
np.allclose(eig_2x2(A)[0], np.linalg.eig(A)[0])

True

In [77]:
np.allclose(eig_2x2(A)[1], np.linalg.eig(A)[1])

True

**Task:** Define matrix B = np.array([[0,1],[-1,0]]) 

In [78]:
B = np.array([[0,1], [-1,0]])

**Task:** Compute the eigenvalues and the eigevectors of matrix 'B' with numpy and with your `'eig_2x2'` function.

In [79]:
eig_2x2(B)

(array([-1.41421356,  1.41421356]),
 array([[-0.57735027, -0.57735027],
        [ 0.81649658, -0.81649658]]))

**Task:** Compare the results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [81]:
np.allclose(eig_2x2(B)[0], np.linalg.eig(B)[0])

False

In [80]:
np.allclose(eig_2x2(B)[1], np.linalg.eig(B)[1])

False

**Task:** Print the eigenvalues and the eigenvectors. Why are the solutions different?

In [83]:
eig_2x2(B)

(array([-1.41421356,  1.41421356]),
 array([[-0.57735027, -0.57735027],
        [ 0.81649658, -0.81649658]]))

In [82]:
np.linalg.eig(B)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        +0.70710678j, 0.        -0.70710678j]]))