**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [3]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

**TASK:** define (2 x 2) matrix 'A' 


In [4]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

**TASK:** define (2 x 2) matrix 'B'

In [5]:
B = np.array([[5, 6], [7, 8]])
B

array([[5, 6],
       [7, 8]])

**TASK:** check the type of 'x'

In [6]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [7]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [9]:
x.shape

(3, 2)

**TASK:** check the type of 'A'

In [10]:
A.shape

(2, 2)

**TASK:** 

"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

In [12]:
def have_same_shape(array_1, array_2):
    
#     PARAMS:
#     array_1 (numpy.ndarray) - first array
#     array_2 (numpy.ndarray) - second array
# RETURN:
#     True - if arrays have same shape
#     False - if arrays do not have same shape

# Also print 'Arrays must have same shape!' when returning False

    if array_1.shape == array_2.shape:
        return('True')
    else:
        return('False. Arrays must have the same shape!')

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [13]:
have_same_shape(A, x)

'False. Arrays must have the same shape!'

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [14]:
have_same_shape(A, B)

'True'

**TASK:** 

"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""

In [16]:
def matrix_addition(A, B):

# Define function 'matrix_addition' which perform matrix addition value by value.

# PARAMS:
#     A (numpy.ndarray) - first array
#     B (numpy.ndarray) - second array
# RETURN:
#     C (numpy.ndarray) - new A+B array

# In this task do not consider broadcasting.
# Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

    if have_same_shape(A, B):
        C = A + B
        return(C)
    else:
        return('Arrays must be the same shape!')

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [17]:
matrix_addition(A, B)

array([[ 6,  8],
       [10, 12]])

**TASK:** 

"""
Define 'multiple_matrix_addition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

In [57]:
def multiple_matrix_addition(lst_of_arr):
    
# Define 'multiple_matrix_addition' function that takes list of arrays as the input and perform array addition

# PARAMS:
#    lst_of_arr (list) - list of numpy.ndarrays
# RETURN:
#     NEW_ARRAY (numpy.ndarray) - new array

# Use 'matrix_addition' function defined before.
        
    S = np.zeros(lst_of_arr[0].shape)
    
    for i in range(len(lst_of_arr)):
        S = matrix_addition(S, lst_of_arr[i])
    return(S)

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [58]:
multiple_matrix_addition([A, A, B, B, B])

array([[17., 22.],
       [27., 32.]])

**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [69]:
def can_multiply(array_a, array_b):
    
# Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

# PARAMS:
#    array_a (numpy.ndarray) - first array
#    array_b (numpy.ndarray) - second array
# RETURN:
#     True - if arrays can be multiplied, also print the shape of the new array
#     False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
    array_a_r, array_a_c = len(array_a), len(array_a[0])
    array_b_r, array_b_c = len(array_b), len(array_b[0])
    
    if array_a_c == array_b_r:
        return(f'The shape of the new array will be {(array_a_r, array_b_c)}.')
    else:
        return('Matrices can not be multiplied.')

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [70]:
can_multiply(A, B)

'The shape of the new array will be (2, 2).'

**TASK:**  define matrix (3 x 2) matrix C

In [71]:
C = np.array([[9, 10], [11, 12], [13, 14]])
C

array([[ 9, 10],
       [11, 12],
       [13, 14]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [72]:
can_multiply(A, C)

'Matrices can not be multiplied.'

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [73]:
can_multiply(C, A)

'The shape of the new array will be (3, 2).'

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [103]:
def matrix_multiplication(array_a, array_b):
    
# Define function 'matrix_multiplication' that multiply two numpy.ndarrays

# PARAMS:
#    array_a (numpy.ndarray) - first array
#    array_b (numpy.ndarray) - second array
# RETURN:
#     NEW_ARRAY (numpy.ndarray) - new A * B array
    
# Do not forget to check if two matrices can be multiplied.

    if can_multiply(array_a, array_b):
        return(array_a.dot(array_b))
    else:
        return('cannot')

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [104]:
matrix_multiplication(C, B)

array([[115, 134],
       [139, 162],
       [163, 190]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [105]:
matrix_multiplication(A, C)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)