# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
np.arange(10, 50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [14]:
a = np.array([1, 2, 0, 0, 4, 0])
a.nonzero()

(array([0, 1, 4], dtype=int64),)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [19]:
np.random.rand(3, 3, 3)

array([[[0.00325098, 0.92080628, 0.34294704],
        [0.38749075, 0.82952848, 0.2500264 ],
        [0.87229562, 0.93748083, 0.73843915]],

       [[0.46655016, 0.19558321, 0.78687717],
        [0.51255745, 0.41707719, 0.57761915],
        [0.3785867 , 0.95513082, 0.48388023]],

       [[0.49519376, 0.25398045, 0.37930048],
        [0.02502319, 0.36797914, 0.11802395],
        [0.34134486, 0.54212823, 0.27476754]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
a = np.random.rand(10, 10)
print(a.min())
print(a.max())

3.070063466004136e-05
0.9836042229390598


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
a = np.random.rand(30)
print(a.mean())

0.5623931418140665


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [38]:
a = np.ones(16).reshape(4, 4)
a[1:3, 1:3] = 0
print(a)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [89]:
a = np.ones(16).reshape(4, 4)
print(a)
a = np.pad(a, pad_width = 1, constant_values = 0)
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [26]:
a = np.diag(np.arange(1, 5), -1)

print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [33]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [49]:
a = np.random.rand(5, 5)

normalized_a = (a - a.min())/ (a.max() - a.min())
print(normalized_a)

[[0.09905032 0.45977521 0.79636704 0.24209444 0.62744359]
 [0.85632873 0.90650848 0.         0.46243527 0.77571375]
 [0.41343497 0.4480216  0.14376124 0.40116549 0.03937026]
 [0.17473124 0.83992643 0.6859605  0.01835079 0.34896863]
 [0.88389465 0.4216939  0.75887085 1.         0.07373389]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [61]:
a = np.arange(10)
a[(3 < a) & (a < 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 29. How to round away from zero a float array ? (★☆☆)

In [10]:
a = np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(a)), a)

array([ 3., -8., -4., 10., -9., -4.,  7., -3., -9., -5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [40]:
a_1 = np.random.rand(5, 5)
a_2 = np.random.rand(5, 5)
np.intersect1d(a_1, a_2)

array([], dtype=float64)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

<ipython-input-41-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [79]:
def generate():
    for n in range(10):
        yield n

a = np.fromiter(generate(), int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [113]:
a = np.linspace(0, 1, 11, False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [128]:
a = np.random.rand(10)
a.sort()
print(a)

[0.0383622  0.15515414 0.22725318 0.24509084 0.25687586 0.57143862
 0.57523264 0.66582154 0.77133363 0.85358715]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [142]:
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

print(np.array_equal(A, B))

False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [182]:
a = np.random.rand(10)
a[np.argmax(a)] = 0
print(a)

[0.098738   0.11346702 0.41944871 0.29117107 0.64251121 0.
 0.47805868 0.84982119 0.55813228 0.12180059]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [30]:
a = np.arange(100)
b = np.random.uniform(0, 100)
index = (np.abs(a - b)).argmin()
print(a[index])

77
76.76000431836306


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
a = np.random.uniform(0, 100, 10).astype(np.int32)
print(a)

[11 65 81 95  2 79 80 53 61  0]


#### 59. How to sort an array by the nth column? (★★☆)

In [73]:
a = np.random.uniform(0, 100, (5, 5))
print(a)

print(a[a[:, 1].argsort()])

[[97.60477743 21.10260935 48.93707059 21.4931487  33.75942652]
 [22.41622133 19.43839204 93.34549148 87.95672077 62.69100323]
 [ 2.66769443 13.74911883 84.52676884 28.22758293 13.4587762 ]
 [91.10486311 49.77772841 39.26307874 68.91539047 67.79456021]
 [96.77602409 85.71855635 30.74672497 40.45197317 83.23917848]]
[[ 2.66769443 13.74911883 84.52676884 28.22758293 13.4587762 ]
 [22.41622133 19.43839204 93.34549148 87.95672077 62.69100323]
 [97.60477743 21.10260935 48.93707059 21.4931487  33.75942652]
 [91.10486311 49.77772841 39.26307874 68.91539047 67.79456021]
 [96.77602409 85.71855635 30.74672497 40.45197317 83.23917848]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [15]:
a = np.random.randint(0, 3, (3,10))
#Evaluate if all elements are True 
print(np.any(a))

True


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [28]:
a = np.array([1, 2, 3, 4, 5])
print(a)

nz = 3

a0 = np.zeros(len(a) + (len(a) - 1) * nz)
print(a0)

a0[::nz + 1] = a
print(a0)

[1 2 3 4 5]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 72. How to swap two rows of an array? (★★★)

In [58]:
a = np.arange(25).reshape(5, 5)
print(a)
a[[0, 1]] = a[[1, 0]]
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [111]:
a = np.random.randint(0,2,25)
print(a)
np.logical_not(a, a)

b = np.random.uniform(-1, 1, 5)
print(b)
print(-b)

[1 0 0 1 0 1 0 1 0 1 1 1 1 0 1 1 0 0 0 0 1 1 1 0 0]
[ 0.46596197  0.29614751 -0.50857899 -0.67508715  0.53378861]
[-0.46596197 -0.29614751  0.50857899  0.67508715 -0.53378861]


#### 83. How to find the most frequent value in an array?

In [260]:
a = np.random.randint(0, 5, 10)
print(f'This is a: \n{a}\n')
a.sort()
print(f'This is sorted a: \n{a}\n')

print(f'This is frequency count: \n{np.bincount(a)}\n')

print(f'This is the most frequent value in a: \n{np.bincount(a).argmax()}')

# Z = np.random.randint(0,10,10)
# print(Z)
# print(np.bincount(Z).argmax())

This is a: 
[4 3 2 4 1 2 3 2 2 2]

This is sorted a: 
[1 2 2 2 2 2 3 3 4 4]

This is frequency count: 
[0 1 5 2 2]

This is the most frequent value in a: 
2


#### 89. How to get the n largest values of an array (★★★)

In [294]:
a = np.random.randint(0, 10, 10)
print(f'This is a: \n{a}\n')

n = 4

print(f'This is the n largest values of a: \n{np.sort(a)[-n:]}')

This is a: 
[4 8 4 0 7 1 6 4 5 1]

This is the n largest values of a: 
[5 6 7 8]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [55]:
a = np.random.randint(0, 2, (6, 3))

unique_a = np.unique(a, axis = 0)
print(unique_a)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]
